repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      # - id: check-yaml  # Disabled due to multi-document YAML files
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: debug-statements
      - id: name-tests-test
        args: ["--pytest-test-first"]
      - id: requirements-txt-fixer
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3.13
        args: ["--line-length=88", "--target-version=py312"]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile=black", "--line-length=88"]

  # - repo: https://github.com/PyCQA/flake8  # Disabled temporarily
  #   rev: 6.0.0
  #   hooks:
  #     - id: flake8

  # - repo: https://github.com/pycqa/pylint  # Disabled temporarily
  #   rev: v3.0.0a7
  #   hooks:
  #     - id: pylint

  # - repo: https://github.com/pre-commit/mirrors-mypy  # Disabled temporarily
  #   rev: v1.5.1
  #   hooks:
  #     - id: mypy

  # - repo: https://github.com/pycqa/bandit  # Disabled temporarily
  #   rev: 1.7.5
  #   hooks:
  #     - id: bandit

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
      - id: pyupgrade
        args: ["--py311-plus"]

  - repo: https://github.com/pycqa/autoflake
    rev: v2.2.0
    hooks:
      - id: autoflake
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--remove-unused-variables",
            "--remove-duplicate-keys",
            "--ignore-init-module-imports",
          ]

  # - repo: https://github.com/pycqa/pydocstyle  # Disabled temporarily
  #   rev: 6.3.0
  #   hooks:
  #     - id: pydocstyle

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        types_or: [yaml, markdown, json]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell
        args: ["--write-changes", "--ignore-words-list=nd,te,ue"]

  - repo: https://github.com/pycqa/doc8
    rev: v1.1.1
    hooks:
      - id: doc8
        args: ["--max-line-length=88"]

  - repo: local
    hooks:
      - id: core-test-check
        name: core-test-check
        entry: python
        language: system
        pass_filenames: false
        always_run: true
        args: ["simple_test.py"]

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ""
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: weekly
  skip: []
  submodules: false
